#
# path=X : (option) X is the package of spideClass, example Example.MyJob
# break  : (option) ignore those jobs that behind this keyword
#
# MySpide             url
# MySpide(para1,...)  url
#

path=E:\Homework\Ing\WebSpide\WebSpideEntry\bin

CaiJia.CYiMuTian(1, 蔬菜)           http://hangqing.ymt.com/jiage_c41
break

CaiJia.CYiMuTian(2, 蔬菜)           http://hangqing.ymt.com/jiage_c41
CaiJia.CYiMuTian(2, 水果)           http://hangqing.ymt.com/jiage_c65
CaiJia.CYiMuTian(2, 花卉盆景)       http://hangqing.ymt.com/jiage_c1
CaiJia.CYiMuTian(2, 坚果干果)       http://hangqing.ymt.com/jiage_c14
CaiJia.CYiMuTian(2, 禽畜牧蛋肉)     http://hangqing.ymt.com/jiage_c32
CaiJia.CYiMuTian(2, 特种养殖)       http://hangqing.ymt.com/jiage_c67
CaiJia.CYiMuTian(2, 食用菌)         http://hangqing.ymt.com/jiage_c39
CaiJia.CYiMuTian(2, 中药材)         http://hangqing.ymt.com/jiage_c69
CaiJia.CYiMuTian(2, 水产)           http://hangqing.ymt.com/jiage_c54
CaiJia.CYiMuTian(2, 粮油)           http://hangqing.ymt.com/jiage_c16
CaiJia.CYiMuTian(2, 经济作物)       http://hangqing.ymt.com/jiage_c114
CaiJia.CYiMuTian(2, 农资)           http://hangqing.ymt.com/jiage_c116
CaiJia.CYiMuTian(2, 农副/副食)      http://hangqing.ymt.com/jiage_c129

